apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fff-sk-learn-random-forest-reg
  namespace: helix-fff
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://4096988a-e589-43bc-8ac6-9cc94fb795bc/0/e5fc69bb42cf4673b711fb3cb6106ec3/artifacts/model
    serviceAccountName: fff-sk-learn-random-forest-reg
